language: rust
env:
    - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
    # Update GTK3 in Docker image
    - WD="$PWD"
    - cd "$HOME"
    - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/gtk-3.18.1-2/deps.txz"
    - tar xf deps.txz
    - cd "$WD"
    - export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
    - export LD_LIBRARY_PATH="$HOME/local/lib/"
    # Build the application
    - cargo build --verbose
